---
output: github_document
---

This folder contains the data and the code supporting the manuscript "".

Please send issues and questions to: [enrico.e.armelloni\@gmail.com](mailto:enrico.e.armelloni@gmail.com){.email}

# Description

The repository conta

## Data

The folder "data" contains files included in the manuscript supplementary materials and some other files generated with code provided in this repository. The essential files needed to start the analysis are:

-   st1_experimental_details.csv summarizes the details of the experiments. This file is needed in the script Step1
-   st2_sample_info contains all the data available in the experiments. This file is needed in the script Step2
-   diet_info contains the formatted information associated to each experiment regarding prey type, prey amount (procedure described in the manuscript) and temperature. This file is needed in the script Step 1.

All the other files contained in the folders are generated with the R scripts provided in this repository.

## Code

### sub-folder R

Contains the code used to perform the analysis. The scripts to replicate results are named with logic order (step1, step2 etc.). Each file contains a short note describing the purpose of the code. *supporting_functions.R* file contains custom functions that are used in the other scripts. *Appendix_S1.R* contains the code used for the simulation study described in Appendix_A

### sub-folder stan

Contains all the stan models for model variants described in the manuscript. Stan files requires compilation, which create large files. This repo only hosts the compiled files for the best model variants to limit the folder size.

# Results

The folder results contains the results generated by the R scripts. Model fits and diagnostics are only provided for the best model variants.
